### ISSUE TITLE
Crash with dynamic surroundings

### ISSUE THREAD

**Issue by DrakeBD** [Glitchfiend/SereneSeasons#102]
[12:28:43] [main/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.NoSuchMethodError: sereneseasons.api.season.SeasonHelper.canSnowAtTempInSeason(Lsereneseasons/api/season/Season;F)Z
	at org.blockartistry.DynSurround.registry.season.SeasonInfoSereneSeasons.showFrostBreath(SeasonInfoSereneSeasons.java:107) ~[SeasonInfoSereneSeasons.class:?]
	at org.blockartistry.DynSurround.registry.SeasonRegistry.showFrostBreath(SeasonRegistry.java:135) ~[SeasonRegistry.class:?]
	at org.blockartistry.DynSurround.client.handlers.effects.FrostBreathEffect.isPossibleToShow(FrostBreathEffect.java:83) ~[FrostBreathEffect.class:?]
	at org.blockartistry.DynSurround.client.handlers.effects.FrostBreathEffect.update(FrostBreathEffect.java:72) ~[FrostBreathEffect.class:?]
	at org.blockartistry.DynSurround.client.effects.EntityEffectHandler.update(EntityEffectHandler.java:108) ~[EntityEffectHandler.class:?]
	at org.blockartistry.DynSurround.client.handlers.FxHandler.lambda$static$1(FxHandler.java:94) ~[FxHandler.class:?]
	at org.blockartistry.lib.collections.CollectionUtils.removeIf(CollectionUtils.java:42) ~[CollectionUtils.class:?]
	at org.blockartistry.DynSurround.client.handlers.FxHandler.process(FxHandler.java:127) ~[FxHandler.class:?]
	at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:173) ~[EffectManager.class:?]
	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:183) ~[EffectManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1707) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by Josral** [comment]
I too am having a crash.  My save game is crashing with versions 1.28 and 1.29 but can play with version 1.26 without a problem.  Adding to this thread because mine involves 'Dynamic Surroundings' as well.

[Minecraft.txt](https://github.com/Glitchfiend/SereneSeasons/files/2624527/Minecraft.txt)

**Comment by Forstride** [comment]
We've updated our API to allow them to fix the issue on their end, so you'll just have to wait until they do so.
