### ISSUE TITLE
IllegalAccessError with OpenJ9

### ISSUE THREAD

**Issue by SanAndreasP** [Glitchfiend/SereneSeasons#138]
**Minecraft Forge** 1.12.2-14.23.5.2768
**Serene Seasons** 1.2.15

I tried to run Serene Seasons with the [OpenJ9 JVM](https://www.eclipse.org/openj9/) and crashed with this stack trace:
```
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError
	at sereneseasons.init.ModHandlers.registerSeasonColourHandlers(ModHandlers.java:66)
	at sereneseasons.init.ModHandlers.init(ModHandlers.java:51)
	at sereneseasons.core.SereneSeasons.preInit(SereneSeasons.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
Caused by: java.lang.IllegalAccessError
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:762)
	... 52 more
Caused by: java.lang.IllegalAccessException: Class 'sereneseasons.init.ModHandlers' no access to: class 'net.minecraft.world.biome.BiomeColorHelper$ColorResolver'
	at java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:436)
	at java.lang.invoke.MethodHandles$Lookup.accessCheckArgRetTypes(MethodHandles.java:670)
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:760)
	... 52 more
```

With the regular Oracle JVM it works.

Here's the complete log: 
https://gist.github.com/SanAndreasP/e74db19ed1a50988cafa25944f749e39

**Comment by ThePerfectLink** [comment]
Any progress on this guy?

**Comment by 3TUSK** [comment]
@ThePerfectLink Update Forge to at least 14.23.5.2815 because this looks like the same as  MinecraftForge/MinecraftForge#5254 which means it's not really a Serene Seasons issue. See also TeamTwilight/twilightforest#660.
