### ISSUE TITLE
weird crash when trying to place season sensor?  / crops not growing...?

### ISSUE THREAD

**Issue by HentaiHamster** [Glitchfiend/SereneSeasons#148]
minecraft 1.12.2 
SereneSeasons-1.12.2-1.2.15-universal.jar 

crashed when placing sensor on my server but server didnt crash...also the block works fine when i relaunch. 
also...season sensor and clock show spring but crops arent growing for some reason?

pastebin for client crash log
https://pastebin.com/5VM08zEN

server log of player crash:

[15:01:45] [Netty Server IO #13/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_201]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Forstride** [comment]
This has nothing to do with Serene Seasons itself
