### ISSUE TITLE
NPE when updating to 1.12.2-1.12.17

### ISSUE THREAD

**Issue by SanAndreasP** [Glitchfiend/SereneSeasons#170]
Forge: 1.12.2-14.23.5.2838
Serene Seasons: 1.12.17

When updating this mod from 1.12.16 to 1.12.17, Minecraft crashes whilst trying to load an existing world:
```
java.lang.NullPointerException: Unexpected error
	at sereneseasons.handler.season.SeasonHandler.getClientSeasonState(SeasonHandler.java:193)
	at sereneseasons.api.season.SeasonHelper.getSeasonState(SeasonHelper.java:31)
	at org.orecruncher.dshuds.compat.SereneSeasonHandler.apply(SereneSeasonHandler.java:44)
	at org.orecruncher.dshuds.compat.SereneSeasonHandler.apply(SereneSeasonHandler.java:37)
	at org.orecruncher.dshuds.Environment.clientTick(Environment.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_906_Environment_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

full log: https://gist.github.com/SanAndreasP/e2a24debe35c7fd0d58a15fbbc57f2ff

**Comment by SanAndreasP** [comment]
Update: I just noticed Dynamic Surroundings HUD in that stack trace... so maybe this is on their part

**Comment by SanAndreasP** [comment]
https://github.com/OreCruncher/DynamicSurroundingsHuds/issues/8
