### ISSUE TITLE
Crash Report (Forge 1.12)

### ISSUE THREAD

**Issue by Hammmah** [Glitchfiend/SereneSeasons#203]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 11/29/19 3:02 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner.appendTo(Joiner.java:109)
	at com.google.common.base.Joiner.appendTo(Joiner.java:154)
	at com.google.common.base.Joiner.join(Joiner.java:197)
	at com.google.common.base.Joiner.join(Joiner.java:187)
	at net.minecraftforge.fml.common.ModMetadata.getAuthorList(ModMetadata.java:81)
	at net.minecraftforge.fml.common.FMLModContainer.getSharedModDescriptor(FMLModContainer.java:714)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:279)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner.appendTo(Joiner.java:109)
	at com.google.common.base.Joiner.appendTo(Joiner.java:154)
	at com.google.common.base.Joiner.join(Joiner.java:197)
	at com.google.common.base.Joiner.join(Joiner.java:187)
	at net.minecraftforge.fml.common.ModMetadata.getAuthorList(ModMetadata.java:81)
	at net.minecraftforge.fml.common.FMLModContainer.getSharedModDescriptor(FMLModContainer.java:714)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:279)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 310328656 bytes (295 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version         | Source                                             | Signature |
	|:----- |:--------------------------- |:--------------- |:-------------------------------------------------- |:--------- |
	| L     | minecraft                   | 1.12.2          | minecraft.jar                                      | None      |
	| L     | mcp                         | 9.42            | minecraft.jar                                      | None      |
	| L     | FML                         | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar                      | None      |
	| L     | forge                       | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar                      | None      |
	| L     | mujmajnkraftsbettersurvival | 1.3.5a          | Better_Survival-1.3.5a.jar                         | None      |
	| L     | biomesoplenty               | 7.0.1.2441      | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None      |
	| L     | campfire                    | 1.2             | campfire-1.12-v1.2.jar                             | None      |
	| L     | comforts                    | 1.4.1.2         | comforts-1.12.2-1.4.1.2.jar                        | None      |
	| L     | craftstudioapi              | 1.0.0           | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None      |
	| L     | elevatorid                  | 1.3.12          | ElevatorMod-1.12.2-1.3.12.jar                      | None      |
	| L     | cfm                         | 6.3.1           | furniture-6.3.1-1.12.2.jar                         | None      |
	| L     | inventorypets               | 2.0.3           | inventorypets-1.12-2.0.3.jar                       | None      |
	| L     | ironbackpacks               | 1.12.2-3.0.8-12 | IronBackpacks-1.12.2-3.0.8-12.jar                  | None      |
	| L     | jei                         | 4.15.0.291      | jei_1.12.2-4.15.0.291.jar                          | None      |
	| L     | journeymap                  | 1.12.2-5.5.5    | journeymap-1.12.2-5.5.5.jar                        | None      |
	| L     | mantle                      | 1.12-1.3.3.55   | Mantle-1.12-1.3.3.55.jar                           | None      |
	| L     | harvestcraft                | 1.12.2zb        | Pam's+HarvestCraft+1.12.2zf.jar                    | None      |
	| L     | sereneseasons               | 1.2.18          | SereneSeasons-1.12.2-1.2.18-universal.jar          | None      |
	| L     | slepingbags                 | 1.0.0           | SpeepingBag++1.0.0.jar                             | None      |
	| L     | toughasnails                | 3.1.0.139       | ToughAsNails-1.12.2-3.1.0.139-universal.jar        | None      |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 4250'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: ATI Radeon HD 4250 GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 3x AMD Phenom(tm) II X4 B55 Processor
I've reinstalled the mod multiple times and it still won't work.

**Comment by Forstride** [comment]
Being listed as a coremod at the top does not mean it's our mod causing the issue.  And judging by the stacktrace, it's not
