### ISSUE TITLE
[1.16.5] Server failed to launch, invalid dist

### ISSUE THREAD

**Issue by No3371** [Glitchfiend/SereneSeasons#299]
```
-- MOD sereneseasons --
Details:
        Mod File: SereneSeasons-1.16.5-4.0.1.88-universal.jar
        Failure message: Serene Seasons (sereneseasons) has failed to load correctly
                java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
        Mod Version: 1.16.4-4.0.0.87
        Mod Issue URL: https://github.com/Glitchfiend/SereneSeasons/issues
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.0.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261] {}
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.0] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_261] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_261] {}
```

**Comment by No3371** [comment]
Looking at the log I also just noticed that the mod version info is 1.16.4-4.0.0.87 in the 1.16.5 file.
