### ISSUE TITLE
crash in 1.16.5 custom world

### ISSUE THREAD

**Issue by matheusvingadouro** [Glitchfiend/SereneSeasons#338]
### What's the issue you encountered?
-the game just crashes in world creation

### How can the issue be reproduced?

-I've just created a custom world with "single biome" option, I've choose the mountains biome, then the game crashed right before I join the world and my player spawn

### Logs

`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 13/06/21 14:36
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at sereneseasons.config.BiomeConfig.usesTropicalSeasons(BiomeConfig.java:64) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperatureInSeason(SeasonHooks.java:66) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperature(SeasonHooks.java:61) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperature(SeasonHooks.java:46) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperatureHook(SeasonHooks.java:37) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at net.minecraft.world.biome.Biome.func_201854_a(Biome.java:177) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
	at net.minecraft.world.biome.Biome.func_201848_a(Biome.java:173) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:484) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:362) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$6767/1868947319.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$6273/1172748538.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}`

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at sereneseasons.config.BiomeConfig.usesTropicalSeasons(BiomeConfig.java:64) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperatureInSeason(SeasonHooks.java:66) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperature(SeasonHooks.java:61) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperature(SeasonHooks.java:46) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at sereneseasons.season.SeasonHooks.getBiomeTemperatureHook(SeasonHooks.java:37) ~[?:1.16.5-4.0.1.91] {re:mixin,re:classloading}
	at net.minecraft.world.biome.Biome.func_201854_a(Biome.java:177) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
	at net.minecraft.world.biome.Biome.func_201848_a(Biome.java:173) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:484) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:362) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$6767/1868947319.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.ServerChunkProviderMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Vingadouro'/235, l='ServerLevel[New World]', x=2.50, y=87.00, z=1.50]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (2,88,0), Chunk: (at 2,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11 game time, 11 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 37923 (now: false), thunder time: 116994 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:multithreading.MinecraftServerMixin,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$6273/1172748538.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1484598288 bytes (1415 MB) / 3992977408 bytes (3808 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.16.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.16
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.16-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |NOSIGNATURE
		SpawnInVillage-1.16.4-1.3.jar                     |Spawn in Village              |spawnvillage                  |1.3                 |DONE      |NOSIGNATURE
		skds_core-0.1.0.jar                               |SKDS Core                     |skds_core                     |0.1.0               |DONE      |NOSIGNATURE
		NoGrow.jar                                        |NoGrowInSomeBiomes            |nogrowinsomebiomes            |1.0.0               |DONE      |NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |DONE      |NOSIGNATURE
		campfire_overhaul-1.16.5-1.0.4.1.jar              |Campfire Overhaul             |campfire_overhaul             |1.0.4.1             |DONE      |NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		jei-1.16.5-7.7.0.98.jar                           |Just Enough Items             |jei                           |7.7.0.98            |DONE      |NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |NOSIGNATURE
		WildFarmCraft.jar                                 |WildFarmCraft                 |wildfarmcraft                 |1.0.0               |DONE      |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.2.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.16-universal.jar                |Forge                         |forge                         |36.1.16             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		water_physics_overhaul-0.1.1.jar                  |Water Physics Overhaul        |wpo                           |0.1.1               |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		TerraForged-1.16.5-0.2.10.jar                     |TerraForged                   |terraforged                   |0.2.10              |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |NOSIGNATURE
		lumberjack-2.1.4.jar                              |LumberJack                    |lumberjack                    |2.1.4               |DONE      |NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |DONE      |NOSIGNATURE
		horse_colors-1.16.5-1.6.0.2.jar                   |Realistic Horse Genetics      |horse_colors                  |1.16.5-1.6.0.2      |DONE      |NOSIGNATURE
	Crash Report UUID: 35b107f6-4cc0-4a35-8da8-9a8acb147570
	Player Count: 1 / 8; [ServerPlayerEntity['Vingadouro'/235, l='ServerLevel[New World]', x=2.50, y=87.00, z=1.50]]
	Data Packs: vanilla, mod:sereneseasons, mod:spawnvillage (incompatible), mod:skds_core, mod:nogrowinsomebiomes, mod:pamhc2trees (incompatible), mod:campfire_overhaul, mod:pamhc2crops (incompatible), mod:waila, mod:jei, mod:astikorcarts, mod:wildfarmcraft, mod:pamhc2foodextended (incompatible), mod:forge, mod:wpo, mod:fastleafdecay (incompatible), mod:terraforged, mod:pamhc2foodcore (incompatible), mod:lumberjack, mod:shutupexperimentalsettings (incompatible), mod:horse_colors, file/BetterSeasons
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2900
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4`

### Mod Version
1.16.5

**Comment by Forstride** [comment]
Delete your config
