### ISSUE TITLE
[crash] setseason autocomplete crash

### ISSUE THREAD

**Issue by Siphalor** [Glitchfiend/SereneSeasons#50]
When pressing tab to autocomplete `/sereneseasons setseason` the server crashes with the following error backtrace:

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.runTask(SourceFile:530)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:922)
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1347)
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52)
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:528)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	... 2 more
```

**Comment by Alaberti** [comment]
Full crashlog: https://paste.dimdev.org/arenegabuq.mccrash

**Comment by Snownee** [comment]
Confirm this problem

**Comment by SpGilbert** [comment]
I can confirm this problem when you try and use tab for the seasons part it gives you a crash. solution have 12 different choices, one for the early, mid and late parts of each season.

**Comment by SpGilbert** [comment]
early_spring, mid_spring, late_spring ,early_summer, mid_summer, late_summer, early_autumn, mid_autumn, late_autumn, early_winter, mid_winter and late_winter. Just make it so when you hit tab after /sereneseasons set season ______.  the 12 mentioned above fill the blank.

**Comment by Forstride** [comment]
Closing this as it's no longer relevant in 1.14/1.15
