### ISSUE TITLE
Crash during worldgen; Infinite snow loop (compatibility w/ Aether II mod)

### ISSUE THREAD

**Issue by CelestialPhoenix** [Glitchfiend/SereneSeasons#78]
Entering an Arctic Peaks biome in the Aether dimension causes a crash to desktop due to infinite looping of snow blocks.

Crashlog https://pastebin.com/c433RVnU
Just a heads up this crash long is over 6000 lines long as it repeats a lot of
```
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
    at net.minecraft.world.World.func_190524_a(World.java:550)
    at net.minecraft.world.World.func_175685_c(World.java:492)
    at net.minecraft.world.World.func_175722_b(World.java:439)
    at net.minecraft.world.World.markAndNotifyBlock(World.java:380)
    at net.minecraft.world.World.func_180501_a(World.java:360)
    at net.minecraft.world.World.func_175698_g(World.java:397)
    at net.minecraft.block.BlockSnow.func_176314_e(BlockSnow.java:105)
    at net.minecraft.block.BlockSnow.func_189540_a(BlockSnow.java:98)
```
With help from the Aether team, we've narrowed it down to Serene Seasons, and tested this with latest versions of Serene Seasons (2.1.6) and Aether II (1.0.110). Forge version: 14.23.4.2707

Link to Aether II Highlands https://minecraft.curseforge.com/projects/the-aether-ii
Link to respective issue on Aether II git https://git.gildedgames.com/GildedGames/Aether-II/issues/969

**Comment by Forstride** [comment]
Can you try this with the latest version of Serene Seasons?  Our snow/ice is now generated through vanilla rather than our own implementation, so this should be fixed.
